datasets:
  TDIUC: # name of the dataset builder
    data_type: images # [images|videos|features] we use features in this case for extracted video features

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        test:
          url: https://storage.googleapis.com/dvqa/TDIUC/TDIUC_sampling.json
          storage: TDIUC/annotations/TDIUC_sampling.json
      images:
          storage: TDIUC/images

